config/routes.rb
Rails.application.routes.draw do
  mount Tolk::Engine => '/tolk', :as => 'tolk' if Rails.env=='development'

  root :to => 'todos#index'

  post 'mailgun/mime' => 'mailgun#mailgun'

  post 'login' => 'login#login'
  get 'login' => 'login#login'
  get 'login/check_expiry' => 'login#check_expiry'
  get 'logout' => 'login#logout'

  get "tickler" => "todos#list_deferred"
  get 'review' => "projects#review"
  get 'calendar' => "calendar#show"
  get 'done' => "stats#done", :as => 'done_overview'

  get 'search' => 'search#index'
  post 'search/results' => 'search#results', :via => 'post'

  get 'data' => "data#index"
  get 'data/csv_notes' => 'data#csv_notes'
  get 'data/yaml_export' => 'data#yaml_export'
  get 'data/xml_export' => 'data#xml_export'
  get 'data/csv_actions' => 'data#csv_actions'

  get 'integrations' => "integrations#index"
  get 'integrations/rest_api' => "integrations#rest_api", :as => 'rest_api_docs'
  post 'integrations/cloudmailin' => 'integrations#cloudmailin'
  get 'integrations/search_plugin' => "integrations#search_plugin", :as => 'search_plugin'

  get 'preferences' => "preferences#index"
  get 'preferences/render_date_format' => "preferences#render_date_format"

  get 'feeds' => "feedlist#index", :as => 'feeds'
  get 'feedlist/get_feeds_for_context' => 'feedlist#get_feeds_for_context'
  get 'feedlist/get_feeds_for_project' => 'feedlist#get_feeds_for_project'

  get 'stats' => 'stats#index'
  get 'stats/actions_done_last12months_data' => 'stats#actions_done_last12months_data'
  get 'stats/actions_done_last_years' => 'stats#actions_done_last_years'
  get 'stats/actions_done_lastyears_data' => 'stats#actions_done_lastyears_data'
  get 'stats/actions_done_last30days_data' => 'stats#actions_done_last30days_data'
  get 'stats/actions_completion_time_data' => 'stats#actions_completion_time_data'
  get 'stats/actions_running_time_data' => 'stats#actions_running_time_data'
  get 'stats/actions_visible_running_time_data' => 'stats#actions_visible_running_time_data'
  get 'stats/actions_open_per_week_data' => 'stats#actions_open_per_week_data'
  get 'stats/context_total_actions_data' => 'stats#context_total_actions_data'
  get 'stats/context_running_actions_data' => 'stats#context_running_actions_data'
  get 'stats/actions_day_of_week_all_data' => 'stats#actions_day_of_week_all_data'
  get 'stats/actions_day_of_week_30days_data' => 'stats#actions_day_of_week_30days_data'
  get 'stats/actions_time_of_day_all_data' => 'stats#actions_time_of_day_all_data'
  get 'stats/actions_time_of_day_30days_data' => 'stats#actions_time_of_day_30days_data'
  get 'stats/show_selected_actions_from_chart/:id' => 'stats#show_selected_actions_from_chart', :as => 'show_actions_from_chart'

  resources :contexts do
    member do
      get 'done_todos'
      get 'all_done_todos'
    end
    collection do
      post 'order'
      get 'done'
    end
    resources :todos
  end

  resources :projects do
    member do
      get 'done_todos'
      get 'all_done_todos'
      get 'set_reviewed'  # TODO: convert to PUT/POST
    end
    collection do
      get 'done'
      post 'order'
      post 'alphabetize'
      post 'actionize'
    end
    resources :todos
  end

  resources :todos do
    member do
      put 'toggle_check'
      put 'toggle_star'
      put 'defer'
      get 'show_notes'
      get 'convert_to_project' # TODO: convert to PUT/POST
      delete 'remove_predecessor' # TODO: convert to PUT/POST
      post 'change_context'
    end
    collection do
      get 'done'
      get 'all_done'
      post 'check_deferred'
      post 'filter_to_context'
      post 'filter_to_project'
      post 'add_predecessor'
    end
  end

  # match /todos/tag and put everything in :name, including extensions like .m and .txt.
  # This means the controller action needs to parse the extension and set format/content type
  # Needed for /todos/tag/first.last.m to work
  get 'todos/tag/:name' => 'todos#tag', :as => :tag, :format => false, :name => /.*/
  
  get 'attachments/:id/:filename' => "todos#attachment"
  get 'tags.autocomplete' => "todos#tags", :format => 'autocomplete'
  get 'todos/done/tag/:name' => "todos#done_tag", :as => :done_tag
  get 'todos/all_done/tag/:name' => "todos#all_done_tag", :as => :all_done_tag
  get 'auto_complete_for_predecessor' => 'todos#auto_complete_for_predecessor'
  get 'mobile' => 'todos#index', :format => 'm'
  get 'm' => 'todos#index', :format => 'm'

  resources :recurring_todos do
    member do
      put 'toggle_check'
      put 'toggle_star'
    end
    collection do
      get 'done'
    end
  end

  resources :users do
    member do
      get 'change_password'
      get 'change_auth_type'
      get 'complete'
      post 'update_password'
      post 'update_auth_type'
      post 'refresh_token'
    end
  end
  get 'signup' => "users#new"

  resources :notes
  resources :preferences

  resources :data do
    collection do
      get :import
      post :csv_map
      post :csv_import
    end
  end

end

app/models/search/search_results.rb
module Search

  class SearchResults
    attr_reader :results

    def initialize(user, terms)
      @user = user
      @terms = "%#{terms}%"
      @results = {}
    end

    def search
      results[:not_complete_todos] = incomplete_todos(@terms)
      results[:complete_todos]     = complete_todos(@terms)
      results[:todos]              = results[:not_complete_todos] + results[:complete_todos]
      results[:projects]           = @user.projects.with_name_or_description(@terms)
      results[:notes]              = @user.notes.with_body(@terms)
      results[:contexts]           = @user.contexts.with_name(@terms)
      results[:tags]               = todo_tags_by_name(@terms)
    end

    def number_of_finds
      results[:todos].size  + results[:projects].size + results[:notes].size + results[:contexts].size + results[:tags].size
    end

    private

    def incomplete_todos(terms)
      @user.todos.
        where("(todos.description LIKE ? OR todos.notes LIKE ?) AND todos.completed_at IS NULL", terms, terms).
        includes(Todo::DEFAULT_INCLUDES).
        reorder("todos.due IS NULL, todos.due ASC, todos.created_at ASC")
    end

    def complete_todos(terms)
      @user.todos.
        where("(todos.description LIKE ? OR todos.notes LIKE ?) AND NOT (todos.completed_at IS NULL)", terms, terms).
        includes(Todo::DEFAULT_INCLUDES).
        reorder("todos.completed_at DESC")
    end

    def todo_tags_by_name(terms)
      Tagging.find_by_sql([
          "SELECT DISTINCT tags.name as name "+
            "FROM tags "+
            "LEFT JOIN taggings ON tags.id = taggings.tag_id "+
            "LEFT JOIN todos ON taggings.taggable_id = todos.id "+
            "WHERE todos.user_id=? "+
            "AND tags.name LIKE ? ", @user.id, terms])
    end

  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  helper :todos, :application, :notes, :projects, :contexts

  def results
    @source_view = params['_source_view'] || 'search'
    @page_title = "TRACKS::Search Results for #{params[:search]}"

    searcher = Search::SearchResults.new(current_user, params[:search])
    searcher.search

    @results = searcher.results
    @count = searcher.number_of_finds

    init_not_done_counts
    init_project_hidden_todo_counts
  end

  def index
    @page_title = "TRACKS::Search"
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_show_results_collection.html.erb
<%
collection = show_results_collection
collection_name ||= 'unknown'
collection_title ||= 'unknown object'
unless collection.empty?
-%>
  <div id="<%=collection_name%>-container" class="container">
    <h2><span id="<%=collection_name%>" class="badge"><%= collection.size %></span><%= collection_title %></h2>
    <%= yield %>
  </div>
<% end -%>

app/views/search/index.html.erb
<div id="display_box_search">
  <%= form_tag(search_results_path, :id => 'search-form') do %>
    <%= text_field_tag(:search, params[:search]) %>
    <%= submit_tag t('common.search') %>
  <% end %>
</div>

app/views/search/results.html.erb
<% if @count == 0 -%>
  <div class="message"><p><%= t('search.no_results') %></p></div>
<% else -%>

  <%= render :layout => 'show_results_collection', :object => @results[:todos], :locals => { :collection_name => "found-todos", :collection_title => t('search.todos_matching_query')} do %>
    <%= render :partial => "todos/todo", :collection => @results[:todos], :locals => { :parent_container_type => 'search', :suppress_context => false, :suppress_project => false, :suppress_edit_button => false } %>
  <% end -%>

  <%= render :layout => 'show_results_collection', :object => @results[:projects], :locals => { :collection_name => "found-project", :collection_title => t('search.projects_matching_query')} do %>
    <%= render :partial => "projects/project_listing", :collection => @results[:projects], :locals => { :suppress_drag_handle => true, :suppress_edit_button => true, :suppress_delete_button => true } %>
  <% end -%>

  <%= render :layout => 'show_results_collection', :object => @results[:notes], :locals => { :collection_name => "found-notes", :collection_title => t('search.notes_matching_query')} do %>
    <%= render :partial => "notes/notes_summary", :collection=> @results[:notes] %>
  <% end -%>

  <%= render :layout => 'show_results_collection', :object => @results[:contexts], :locals => { :collection_name => "found-contexts", :collection_title => t('search.contexts_matching_query')} do %>
    <%= render :partial => "contexts/context_listing", :collection => @results[:contexts], :locals => { :suppress_drag_handle => true, :suppress_edit_button => true } %>
  <% end -%>

  <%= render :layout => 'show_results_collection', :object => @results[:tags], :locals => { :collection_name => "found-tags", :collection_title => t('search.tags_matching_query')} do %>
    <span class="tags"><% @results[:tags].each do |tag| -%>
        <span class="tag"><%= link_to tag.name, tag_path(tag.name) -%></span>
      <% end %>
    </span><br/><br/>
  <% end -%>

<% end -%>