config/routes.rb
Rails.application.routes.draw do
  mount Tolk::Engine => '/tolk', :as => 'tolk' if Rails.env=='development'

  root :to => 'todos#index'

  post 'mailgun/mime' => 'mailgun#mailgun'

  post 'login' => 'login#login'
  get 'login' => 'login#login'
  get 'login/check_expiry' => 'login#check_expiry'
  get 'logout' => 'login#logout'

  get "tickler" => "todos#list_deferred"
  get 'review' => "projects#review"
  get 'calendar' => "calendar#show"
  get 'done' => "stats#done", :as => 'done_overview'

  get 'search' => 'search#index'
  post 'search/results' => 'search#results', :via => 'post'

  get 'data' => "data#index"
  get 'data/csv_notes' => 'data#csv_notes'
  get 'data/yaml_export' => 'data#yaml_export'
  get 'data/xml_export' => 'data#xml_export'
  get 'data/csv_actions' => 'data#csv_actions'

  get 'integrations' => "integrations#index"
  get 'integrations/rest_api' => "integrations#rest_api", :as => 'rest_api_docs'
  post 'integrations/cloudmailin' => 'integrations#cloudmailin'
  get 'integrations/search_plugin' => "integrations#search_plugin", :as => 'search_plugin'

  get 'preferences' => "preferences#index"
  get 'preferences/render_date_format' => "preferences#render_date_format"

  get 'feeds' => "feedlist#index", :as => 'feeds'
  get 'feedlist/get_feeds_for_context' => 'feedlist#get_feeds_for_context'
  get 'feedlist/get_feeds_for_project' => 'feedlist#get_feeds_for_project'

  get 'stats' => 'stats#index'
  get 'stats/actions_done_last12months_data' => 'stats#actions_done_last12months_data'
  get 'stats/actions_done_last_years' => 'stats#actions_done_last_years'
  get 'stats/actions_done_lastyears_data' => 'stats#actions_done_lastyears_data'
  get 'stats/actions_done_last30days_data' => 'stats#actions_done_last30days_data'
  get 'stats/actions_completion_time_data' => 'stats#actions_completion_time_data'
  get 'stats/actions_running_time_data' => 'stats#actions_running_time_data'
  get 'stats/actions_visible_running_time_data' => 'stats#actions_visible_running_time_data'
  get 'stats/actions_open_per_week_data' => 'stats#actions_open_per_week_data'
  get 'stats/context_total_actions_data' => 'stats#context_total_actions_data'
  get 'stats/context_running_actions_data' => 'stats#context_running_actions_data'
  get 'stats/actions_day_of_week_all_data' => 'stats#actions_day_of_week_all_data'
  get 'stats/actions_day_of_week_30days_data' => 'stats#actions_day_of_week_30days_data'
  get 'stats/actions_time_of_day_all_data' => 'stats#actions_time_of_day_all_data'
  get 'stats/actions_time_of_day_30days_data' => 'stats#actions_time_of_day_30days_data'
  get 'stats/show_selected_actions_from_chart/:id' => 'stats#show_selected_actions_from_chart', :as => 'show_actions_from_chart'

  resources :contexts do
    member do
      get 'done_todos'
      get 'all_done_todos'
    end
    collection do
      post 'order'
      get 'done'
    end
    resources :todos
  end

  resources :projects do
    member do
      get 'done_todos'
      get 'all_done_todos'
      get 'set_reviewed'  # TODO: convert to PUT/POST
    end
    collection do
      get 'done'
      post 'order'
      post 'alphabetize'
      post 'actionize'
    end
    resources :todos
  end

  resources :todos do
    member do
      put 'toggle_check'
      put 'toggle_star'
      put 'defer'
      get 'show_notes'
      get 'convert_to_project' # TODO: convert to PUT/POST
      delete 'remove_predecessor' # TODO: convert to PUT/POST
      post 'change_context'
    end
    collection do
      get 'done'
      get 'all_done'
      post 'check_deferred'
      post 'filter_to_context'
      post 'filter_to_project'
      post 'add_predecessor'
    end
  end

  # match /todos/tag and put everything in :name, including extensions like .m and .txt.
  # This means the controller action needs to parse the extension and set format/content type
  # Needed for /todos/tag/first.last.m to work
  get 'todos/tag/:name' => 'todos#tag', :as => :tag, :format => false, :name => /.*/
  
  get 'attachments/:id/:filename' => "todos#attachment"
  get 'tags.autocomplete' => "todos#tags", :format => 'autocomplete'
  get 'todos/done/tag/:name' => "todos#done_tag", :as => :done_tag
  get 'todos/all_done/tag/:name' => "todos#all_done_tag", :as => :all_done_tag
  get 'auto_complete_for_predecessor' => 'todos#auto_complete_for_predecessor'
  get 'mobile' => 'todos#index', :format => 'm'
  get 'm' => 'todos#index', :format => 'm'

  resources :recurring_todos do
    member do
      put 'toggle_check'
      put 'toggle_star'
    end
    collection do
      get 'done'
    end
  end

  resources :users do
    member do
      get 'change_password'
      get 'change_auth_type'
      get 'complete'
      post 'update_password'
      post 'update_auth_type'
      post 'refresh_token'
    end
  end
  get 'signup' => "users#new"

  resources :notes
  resources :preferences

  resources :data do
    collection do
      get :import
      post :csv_map
      post :csv_import
    end
  end

end

app/views/shared/_add_new_item_form.html.erb
<%
@initial_context_name = @context.name if @context
@initial_context_name ||= @project.default_context.name unless @project.nil? || @project.default_context.nil?
@initial_context_name ||= @contexts.active.first.name unless @contexts.active.first.nil?
@initial_context_name ||= @contexts.first.name unless @contexts.first.nil?
@initial_project_name = @project.name unless @project.nil?
@initial_tags ||= @default_tags
@initial_tags ||= @project.default_tags unless @project.nil?
-%>
<div id="todo_new_action_container">

  <div id="toggle_forms" class="toggle_forms">
    <a title="<%= t('shared.hide_action_form_title') %>" accesskey="n" href="#" id="toggle_action_new"><%= t('shared.hide_form') %></a> |
    <a title="<%= t('shared.toggle_multi_title') %>" accesskey="m" href="#" id="toggle_multi"><%= t('shared.toggle_multi') %></a>
  </div>

  <%= render :partial => 'todos/new_todo_form', :object => Todo.new %>
  <%= render :partial => 'todos/new_multi_todo_form', :object => Todo.new %>

</div>

app/views/shared/_flash.html.erb
<div id="message_holder">
<% if flash.empty? -%>
  <h4 id="flash" class="alert" style="display:none"></h4>
<% else -%>
  <% flash.each do |key,value| -%>
    <h4 id="flash" class='alert <%= key %>'><%= value %></h4>
  <% end -%>
<% end -%>
</div>

app/views/shared/_flash.m.erb
<div id="message_holder">
<% if flash.empty? -%>
  <h4 id="flash" class="alert" style="display:none"></h4>
<% else -%>
  <% flash.each do |key,value| -%>
    <h4 id="flash" class='alert <%= key %>'><%= value.html_safe %></h4>
  <% end -%>
<% end -%>
</div>

app/views/shared/_footer.html.erb
<div class="bootstrap">
  <div class="footer">
    <%= t('footer.send_feedback', :version => TRACKS_VERSION) %>
    <span class="footer-line">
      <a href="https://github.com/TracksApp/tracks/issues"><%= t('common.bugs')%></a> |
      <a href="https://github.com/TracksApp/tracks/wiki"><%= t('common.wiki')%></a> |
      <a href="http://groups.google.com/group/TracksApp"><%= t('common.mailing_list')%></a> |
      <a href="http://www.getontracks.org/"><%= t('common.website')%></a> |
      <a href="http://www.getontracks.org/development/"><%= t('common.contribute')%></a> |
      <%= link_to(t('layouts.navigation.mobile'), todos_path(:format => 'm')) %>
    </span>
  </div>
</div>

app/views/shared/_footer.m.erb
<div class="footer"><p>Tracks <%= TRACKS_VERSION %> Mobile | <%= (link_to(t('layouts.mobile_navigation.full'),  todos_path(:format => 'html'))) -%></p></div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand legacy-ui">
        <% if @count -%>
        <span id="badge_count" class="badge"><%= @count %></span>
        <% end -%>
        <%= l(Time.zone.today, :format => current_user.prefs.title_date_format) %>
      </div>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= navigation_link(t('layouts.navigation.home'), root_path, {:accesskey => "t", :title => t('layouts.navigation.home_title')} ) %></li>
        <li><%= navigation_link(t('layouts.navigation.starred'), tag_path("starred"), :title => t('layouts.navigation.starred_title')) %></li>
        <li><%= navigation_link(t('common.projects'), projects_path, {:accesskey=>"p", :title=>t('layouts.navigation.projects_title')} ) %></li>
        <li><%= navigation_link(t('layouts.navigation.tickler'), tickler_path, {:accesskey =>"k", :title => t('layouts.navigation.tickler_title')} ) %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= t('layouts.navigation.organize') %> <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= navigation_link( t('common.contexts'), contexts_path, {:accesskey=>"c", :title=>t('layouts.navigation.contexts_title')} ) %></li>
            <li><%= navigation_link( t('common.notes'), notes_path, {:accesskey => "o", :title => t('layouts.navigation.notes_title')} ) %></li>
            <li><%= navigation_link( t('common.review'), review_path, {:accesskey => "r", :title => t('layouts.navigation.review_title')} ) %></li>
            <li><%= navigation_link( t('layouts.navigation.recurring_todos'), {:controller => "recurring_todos", :action => "index"}, :title => t('layouts.navigation.recurring_todos_title')) %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" id="menu_view_link" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= t('layouts.navigation.view') %> <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= navigation_link( t('layouts.navigation.calendar'), calendar_path, :title => t('layouts.navigation.calendar_title')) %></li>
            <li><%= navigation_link( t('layouts.navigation.completed_tasks'), done_overview_path, {:accesskey=>"d", :title=>t('layouts.navigation.completed_tasks_title')} ) %></li>
            <li><%= navigation_link( t('layouts.navigation.feeds'), feeds_path, :title => t('layouts.navigation.feeds_title')) %></li>
            <li><%= navigation_link( t('layouts.navigation.stats'), stats_path, :title => t('layouts.navigation.stats_title')) %></li>
            <li class="divider"></li>
            <li id="menu_view_toggle_contexts"><%= link_to(t('layouts.toggle_contexts'), "#", {:title => t('layouts.toggle_contexts_title'), :id => "toggle-contexts-nav"}) %></li>
            <li><%= link_to(t('layouts.toggle_notes'), "#", {:accesskey => "S", :title => t('layouts.toggle_notes_title'), :id => "toggle-notes-nav"}) %></li>
            <%= group_view_by_menu_entry %>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= t('layouts.navigation.admin') %> <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= navigation_link( t('layouts.navigation.preferences'), preferences_path, {:accesskey => "u", :title => t('layouts.navigation.preferences_title')} ) %></li>
            <li><%= navigation_link( t('layouts.navigation.export'), data_path, {:accesskey => "e", :title => t('layouts.navigation.export_title')} ) %></li>
            <li><%= navigation_link( t('layouts.navigation.import'), import_data_path, {:accesskey => "i", :title => t('layouts.navigation.import_title')} ) %></li>
            <% if current_user.is_admin? -%>
            <li><%= navigation_link(t('layouts.navigation.manage_users'), users_path, {:accesskey => "a", :title => t('layouts.navigation.manage_users_title')} ) %></li>
            <% end -%>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= t('layouts.navigation.help') %> <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to t('layouts.navigation.integrations_'), integrations_path %></li>
            <li><%= link_to t('layouts.navigation.api_docs'), rest_api_docs_path %></li>
          </ul>
        </li>
        <li><%= navigation_link(image_tag("system-search.png", :size => "16X16", :border => 0), search_path, :title => t('layouts.navigation.search')) %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to("#{t('common.logout')} (#{current_user.display_name}) &raquo;".html_safe, logout_path) %>
        </li>
      </ul>
    </div>
  </div>
</nav>