config/routes.rb
Rails.application.routes.draw do
  mount Tolk::Engine => '/tolk', :as => 'tolk' if Rails.env=='development'

  root :to => 'todos#index'

  post 'mailgun/mime' => 'mailgun#mailgun'

  post 'login' => 'login#login'
  get 'login' => 'login#login'
  get 'login/check_expiry' => 'login#check_expiry'
  get 'logout' => 'login#logout'

  get "tickler" => "todos#list_deferred"
  get 'review' => "projects#review"
  get 'calendar' => "calendar#show"
  get 'done' => "stats#done", :as => 'done_overview'

  get 'search' => 'search#index'
  post 'search/results' => 'search#results', :via => 'post'

  get 'data' => "data#index"
  get 'data/csv_notes' => 'data#csv_notes'
  get 'data/yaml_export' => 'data#yaml_export'
  get 'data/xml_export' => 'data#xml_export'
  get 'data/csv_actions' => 'data#csv_actions'

  get 'integrations' => "integrations#index"
  get 'integrations/rest_api' => "integrations#rest_api", :as => 'rest_api_docs'
  post 'integrations/cloudmailin' => 'integrations#cloudmailin'
  get 'integrations/search_plugin' => "integrations#search_plugin", :as => 'search_plugin'

  get 'preferences' => "preferences#index"
  get 'preferences/render_date_format' => "preferences#render_date_format"

  get 'feeds' => "feedlist#index", :as => 'feeds'
  get 'feedlist/get_feeds_for_context' => 'feedlist#get_feeds_for_context'
  get 'feedlist/get_feeds_for_project' => 'feedlist#get_feeds_for_project'

  get 'stats' => 'stats#index'
  get 'stats/actions_done_last12months_data' => 'stats#actions_done_last12months_data'
  get 'stats/actions_done_last_years' => 'stats#actions_done_last_years'
  get 'stats/actions_done_lastyears_data' => 'stats#actions_done_lastyears_data'
  get 'stats/actions_done_last30days_data' => 'stats#actions_done_last30days_data'
  get 'stats/actions_completion_time_data' => 'stats#actions_completion_time_data'
  get 'stats/actions_running_time_data' => 'stats#actions_running_time_data'
  get 'stats/actions_visible_running_time_data' => 'stats#actions_visible_running_time_data'
  get 'stats/actions_open_per_week_data' => 'stats#actions_open_per_week_data'
  get 'stats/context_total_actions_data' => 'stats#context_total_actions_data'
  get 'stats/context_running_actions_data' => 'stats#context_running_actions_data'
  get 'stats/actions_day_of_week_all_data' => 'stats#actions_day_of_week_all_data'
  get 'stats/actions_day_of_week_30days_data' => 'stats#actions_day_of_week_30days_data'
  get 'stats/actions_time_of_day_all_data' => 'stats#actions_time_of_day_all_data'
  get 'stats/actions_time_of_day_30days_data' => 'stats#actions_time_of_day_30days_data'
  get 'stats/show_selected_actions_from_chart/:id' => 'stats#show_selected_actions_from_chart', :as => 'show_actions_from_chart'

  resources :contexts do
    member do
      get 'done_todos'
      get 'all_done_todos'
    end
    collection do
      post 'order'
      get 'done'
    end
    resources :todos
  end

  resources :projects do
    member do
      get 'done_todos'
      get 'all_done_todos'
      get 'set_reviewed'  # TODO: convert to PUT/POST
    end
    collection do
      get 'done'
      post 'order'
      post 'alphabetize'
      post 'actionize'
    end
    resources :todos
  end

  resources :todos do
    member do
      put 'toggle_check'
      put 'toggle_star'
      put 'defer'
      get 'show_notes'
      get 'convert_to_project' # TODO: convert to PUT/POST
      delete 'remove_predecessor' # TODO: convert to PUT/POST
      post 'change_context'
    end
    collection do
      get 'done'
      get 'all_done'
      post 'check_deferred'
      post 'filter_to_context'
      post 'filter_to_project'
      post 'add_predecessor'
    end
  end

  # match /todos/tag and put everything in :name, including extensions like .m and .txt.
  # This means the controller action needs to parse the extension and set format/content type
  # Needed for /todos/tag/first.last.m to work
  get 'todos/tag/:name' => 'todos#tag', :as => :tag, :format => false, :name => /.*/
  
  get 'attachments/:id/:filename' => "todos#attachment"
  get 'tags.autocomplete' => "todos#tags", :format => 'autocomplete'
  get 'todos/done/tag/:name' => "todos#done_tag", :as => :done_tag
  get 'todos/all_done/tag/:name' => "todos#all_done_tag", :as => :all_done_tag
  get 'auto_complete_for_predecessor' => 'todos#auto_complete_for_predecessor'
  get 'mobile' => 'todos#index', :format => 'm'
  get 'm' => 'todos#index', :format => 'm'

  resources :recurring_todos do
    member do
      put 'toggle_check'
      put 'toggle_star'
    end
    collection do
      get 'done'
    end
  end

  resources :users do
    member do
      get 'change_password'
      get 'change_auth_type'
      get 'complete'
      post 'update_password'
      post 'update_auth_type'
      post 'refresh_token'
    end
  end
  get 'signup' => "users#new"

  resources :notes
  resources :preferences

  resources :data do
    collection do
      get :import
      post :csv_map
      post :csv_import
    end
  end

end

app/controllers/data_controller.rb
class DataController < ApplicationController

  require 'csv'

  def index
    @page_title = "TRACKS::Export"
  end

  def import

  end

  def csv_map
    if params[:file].blank?
      flash[:notice] = "File can't be blank"
      redirect_to :back
    else
      @import_to = params[:import_to]

      begin
        #get column headers and format as [['name', column_number]...]
        i = -1
        @headers = import_headers(params[:file].path).collect { |v| [v, i+=1] }
        @headers.unshift ['',i]
      rescue Exception => e
        flash[:error] = "Invalid CVS: could not read headers: #{e}"
        redirect_to :back
        return
      end

      #save file for later
      begin
        uploaded_file = params[:file]
        @filename = sanitize_filename(uploaded_file.original_filename)
        path_and_file = Rails.root.join('public', 'uploads', 'csv', @filename)
        File.open(path_and_file, "wb") { |f| f.write(uploaded_file.read) }
      rescue Exception => e
        flash[:error] = "Could not save uploaded CSV (#{path_and_file}). Can Tracks write to the upload directory? #{e}"
        redirect_to :back
        return
      end

      case @import_to
      when 'projects'
        @labels = [:name, :description]
      when 'todos'
        @labels = [:description, :context, :project, :notes, :created_at, :due, :completed_at]
      else
        flash[:error] = "Invalid import destination"
        redirect_to :back
      end
      respond_to do |format|
        format.html
      end
    end
  end

  def csv_import
    begin
      filename = sanitize_filename(params[:file])
      path_and_file = Rails.root.join('public', 'uploads', 'csv', filename)
      case params[:import_to]
      when 'projects'
        count = Project.import path_and_file, params, current_user
        flash[:notice] = "#{count} Projects imported"
      when 'todos'
        count = Todo.import path_and_file, params, current_user
        flash[:notice] = "#{count} Todos imported"
      else
        flash[:error] = t('data.invalid_import_destination')
      end
    rescue Exception => e
      flash[:error] = t('data.invalid_import_destination') + ": #{e}"
    end
    File.delete(path_and_file)
    redirect_to import_data_path
  end

  def import_headers(file)
    CSV.foreach(file, headers: false) do |row|
      return row
    end
  end

  def export
    # Show list of formats for export
  end

  # Thanks to a tip by Gleb Arshinov
  # <http://lists.rubyonrails.org/pipermail/rails/2004-November/000199.html>
  def yaml_export
    all_tables = {}

    all_tables['todos'] = current_user.todos.includes(:tags).load
    all_tables['contexts'] = current_user.contexts.load
    all_tables['projects'] = current_user.projects.load

    todo_tag_ids = Tag.find_by_sql([
        "SELECT DISTINCT tags.id "+
          "FROM tags, taggings, todos "+
          "WHERE todos.user_id=? "+
          "AND tags.id = taggings.tag_id " +
          "AND taggings.taggable_id = todos.id ", current_user.id])
    rec_todo_tag_ids = Tag.find_by_sql([
        "SELECT DISTINCT tags.id "+
          "FROM tags, taggings, recurring_todos "+
          "WHERE recurring_todos.user_id=? "+
          "AND tags.id = taggings.tag_id " +
          "AND taggings.taggable_id = recurring_todos.id ", current_user.id])
    tags = Tag.where("id IN (?) OR id IN (?)", todo_tag_ids, rec_todo_tag_ids)
    taggings = Tagging.where("tag_id IN (?) OR tag_id IN(?)", todo_tag_ids, rec_todo_tag_ids)

    all_tables['tags'] = tags.load
    all_tables['taggings'] = taggings.load
    all_tables['notes'] = current_user.notes.load
    all_tables['recurring_todos'] = current_user.recurring_todos.load

    result = all_tables.to_yaml
    result.gsub!(/\n/, "\r\n")   # TODO: general functionality for line endings
    send_data(result, :filename => "tracks_backup.yml", :type => 'text/plain')
  end

  # export all actions as csv
  def csv_actions
    content_type = 'text/csv'
    CSV.generate(result = "") do |csv|
      csv << ["id", "Context", "Project", "Description", "Notes", "Tags",
        "Created at", "Due", "Completed at", "User ID", "Show from",
        "state"]
      current_user.todos.includes(:context, :project, :taggings, :tags).each do |todo|
        csv << [todo.id, todo.context.name,
          todo.project_id.nil? ? "" : todo.project.name,
          todo.description,
          todo.notes, todo.tags.collect{|t| t.name}.join(', '),
          todo.created_at.to_formatted_s(:db),
          todo.due? ? todo.due.to_formatted_s(:db) : "",
          todo.completed_at? ? todo.completed_at.to_formatted_s(:db) : "",
          todo.user_id,
          todo.show_from? ? todo.show_from.to_formatted_s(:db) : "",
          todo.state]
      end
    end
    send_data(result, :filename => "todos.csv", :type => content_type)
  end

  # export all notes as csv
  def csv_notes
    content_type = 'text/csv'
    CSV.generate(result = "") do |csv|
      csv << ["id", "User ID", "Project", "Note",
        "Created at", "Updated at"]
      # had to remove project include because it's association order is leaking
      # through and causing an ambiguous column ref even with_exclusive_scope
      # didn't seem to help -JamesKebinger
      current_user.notes.reorder("notes.created_at").each do |note|
        # Format dates in ISO format for easy sorting in spreadsheet Print
        # context and project names for easy viewing
        csv << [note.id, note.user_id,
          note.project_id = note.project_id.nil? ? "" : note.project.name,
          note.body, note.created_at.to_formatted_s(:db),
          note.updated_at.to_formatted_s(:db)]
      end
    end
    send_data(result, :filename => "notes.csv", :type => content_type)
  end

  def xml_export
    todo_tag_ids = Tag.find_by_sql([
        "SELECT DISTINCT tags.id "+
          "FROM tags, taggings, todos "+
          "WHERE todos.user_id=? "+
          "AND tags.id = taggings.tag_id " +
          "AND taggings.taggable_id = todos.id ", current_user.id])
    rec_todo_tag_ids = Tag.find_by_sql([
        "SELECT DISTINCT tags.id "+
          "FROM tags, taggings, recurring_todos "+
          "WHERE recurring_todos.user_id=? "+
          "AND tags.id = taggings.tag_id " +
          "AND taggings.taggable_id = recurring_todos.id ", current_user.id])
    tags = Tag.where("id IN (?) OR id IN (?)", todo_tag_ids, rec_todo_tag_ids)
    taggings = Tagging.where("tag_id IN (?) OR tag_id IN(?)", todo_tag_ids, rec_todo_tag_ids)

    result = "<?xml version=\"1.0\" encoding=\"UTF-8\" ?><tracks_data>"
    result << current_user.todos.to_xml(:skip_instruct => true)
    result << current_user.contexts.to_xml(:skip_instruct => true)
    result << current_user.projects.to_xml(:skip_instruct => true)
    result << tags.to_xml(:skip_instruct => true)
    result << taggings.to_xml(:skip_instruct => true)
    result << current_user.notes.to_xml(:skip_instruct => true)
    result << current_user.recurring_todos.to_xml(:skip_instruct => true)
    result << "</tracks_data>"
    send_data(result, :filename => "tracks_data.xml", :type => 'text/xml')
  end

  def yaml_form
    # Draw the form to input the YAML text data
  end

  # adjusts time to utc
  def adjust_time(timestring)
    if (timestring=='') or ( timestring == nil)
      return nil
    else
      return Time.parse(timestring + 'UTC')
    end
  end

  def yaml_import
    raise "YAML loading is disabled"
  end

  private
  def sanitize_filename(filename)
    filename.gsub(/[^0-9A-z.\-]/, '_')
  end

end

app/helpers/data_helper.rb
module DataHelper
end

app/views/data/csv_map.html.erb
<h3>Map fields to be imported<h3>
<%= form_tag csv_import_data_path do %>
	<% @labels.each do |l| %>
		<%= label_tag l %>:
		<%= select_tag(l, options_for_select(@headers) ) %>
		<br>
	<% end %>
	<%= hidden_field_tag :file, @filename %>
	<%= hidden_field_tag :import_to, @import_to %>
	<%= submit_tag "Import" %>
<% end %>

app/views/data/import.html.erb
<div id="display_box">
  <div id="feeds">
    <div id="feedlegend">
      <h2>Importing data</h2>
      <div>
        <h3>Please upload your CSV file</h3>
        <%= form_tag csv_map_data_path, :id => 'upload_form', multipart: true do %>
          <label for="import_to">Import to:</label>
          <%= select_tag(:import_to, options_for_select([['Projects', 'projects'], ['Todos', 'todos']], 1) ) %>
          <br><br>
          <%= file_field_tag :file %>
          <%= submit_tag "Upload", :id => "upload_form_submit" %>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/data/index.de.html.erb
<div id="display_box">
  <div id="feeds">
    <div id="feedlegend">
      <h3>Daten exportieren</h3>
      <p>Sie k&ouml;nnen zwischen den folgenden Formaten w&auml;hlen:</p>
      <ul>
        <li><strong>YAML: </strong>F&uuml;r den Daten-Import bevorzugt.<br/><i>Bitte beachten Sie, dass der YAML-Import zur Zeit noch experimentelle Funktionalit&auml;t darstellt. Nutzen Sie diese Option also nicht. um kritische Daten zu sichern.</i></li>
        <li><strong>CSV: </strong>Am besten f&uuml;r den Export in eine Tabellen-Kalkulation oder &auml;hnliche Auswertungs-Software geeignet</li>
        <li><strong>XML: </strong>Am besten f&uuml;r den Daten-Import oder automatische Weiterverarbeitung</li>
      </ul>
    </div>
    <br/><br/>
    <table class="export_table">
      <tr>
        <th>Beschreibung</th>
        <th>Download link</th>
      </tr>
      <tr>
        <td>YAML-Datei mit all Ihren Aktionen, Umgebungen, Projekten, Tags und Notizen</td>
        <td><%= link_to "YAML Datei", :controller => 'data', :action => 'yaml_export' %></td>
      </tr>
      <tr>
        <td>CSV-Datei mit all Ihren Aktionen, benannten Umgebungen und Projekten</td>
        <td><%= link_to "CSV Dile (Aktionen, Umgebungen und Projekte)", :controller => 'data', :action => 'csv_actions' %></td>
      </tr>
      <tr>
        <td>CSV-Datei mit all Ihren Notizen</td>
        <td><%= link_to "CSV Datei (nur Notizen)", :controller => 'data', :action => 'csv_notes' %></td>
      </tr>
      <tr>
        <td>XML-Datei mit all Ihren Aktionen, Umgebungen, Projekten, Tags und Notizen</td>
        <td><%= link_to "XML file (actions only)", :controller => 'data', :action => 'xml_export' %></td>
      </tr>
    </table>
  </div><!-- End of feeds -->
</div>

app/views/data/index.en.html.erb
<div id="display_box">
  <div id="feeds">
    <div id="feedlegend">
      <h3>Exporting data</h3>
      <p>You can choose between the following formats:</p>
      <ul>
        <li><strong>YAML: </strong>Best for exporting data. <br/><i>Please note that  importing YAML files is currently supported only in experimentally. Do not rely on it for backing up critical data.</i></li>
        <li><strong>CSV: </strong>Best for importing into spreadsheet or data analysis software</li>
        <li><strong>XML: </strong>Best for importing or repurposing the data</li>
      </ul>
    </div>
    <br/><br/>
    <table class="export_table">
      <tr>
        <th>Description</th>
        <th>Download link</th>
      </tr>
      <tr>
        <td>YAML file containing all your actions, contexts, projects, tags and notes</td>
        <td><%= link_to "YAML file", data_yaml_export_path %></td>
      </tr>
      <tr>
        <td>CSV file containing all of your actions, with named contexts and projects</td>
        <td><%= link_to "CSV file (actions, contexts and projects)", data_csv_actions_path %></td>
      </tr>
      <tr>
        <td>CSV file containing all your notes</td>
        <td><%= link_to "CSV file (notes only)", data_csv_notes_path %></td>
      </tr>
      <tr>
        <td>XML file containing all your actions, contexts, projects, tags and notes</td>
        <td><%= link_to "XML file (actions only)", data_xml_export_path %></td>
      </tr>
    </table>
  </div><!-- End of feeds -->
</div>

app/views/data/index.es.html.erb
<div id="display_box">
  <div id="feeds">
    <div id="feedlegend">
      <h3>Exportar datos</h3>
      <p>Puede escoger entre los siguientes formatos:</p>
      <ul>
        <li><strong>YAML: </strong>Mejor formato para exportar datos. <br/><i>Por favor tenga en cuenta que la importación de ficheros YAML actualmente esta soportada de forma experimental. No confíe en este formato para hacer copias de seguridad de datos importantes.</i></li>
        <li><strong>CSV: </strong>Mejor formato para importar en una hoja de cálculo o en programas de análisis de datos.</li>
        <li><strong>XML: </strong>Mejor formato para transformar los datos a otro formato</li>
      </ul>
    </div>
    <br/><br/>
    <table class="export_table">
      <tr>
        <th>Descripción</th>
        <th>Enlace de descarga</th>
      </tr>
      <tr>
        <td>Fichero YAML con todas sus acciones, contextos, proyectos, etiquetas y notas</td>
        <td><%= link_to "Fichero YAML", data_yaml_export_path %></td>
      </tr>
      <tr>
        <td>Fichero CSV con todas sus acciones, con contextos por nombre y proyectos</td>
        <td><%= link_to "Fichero CSV (acciones, contextos y proyectos)", data_csv_actions_path %></td>
      </tr>
      <tr>
        <td>Fichero CSV con todas sus notas</td>
        <td><%= link_to "Fichero CSV (sólo notas)", data_csv_notes_path %></td>
      </tr>
      <tr>
        <td>Fichero XML con todas sus acciones, contextos, proyectos, etiquetas y notas</td>
        <td><%= link_to "Fichero XML", data_xml_export_path %></td>
      </tr>
    </table>
  </div><!-- End of feeds -->
</div>

app/views/data/yaml_form.de.html.erb
<div id="display_box">
  <div id="feeds">
    <div id="feedlegend">
      <p><b>Vorsicht</b>: vor dem Import der YAML Datei werden alle Daten in Ihrer Datenbank gel&ouml;scht.
        Falls Sie entsprechenden Zugriff auf Ihre Datenbank haben, empfiehlt es sich, ein Backup anzulegen,
        bevor Sie fortfahren.
      </p>
      <p>F&uuml;gen Sie den Inhalt der kopierten YAML Datei in das untenstehende Formular ein:</p>
    </div>
    <p>
      <%= form_for :import, @import, :url => {:controller => 'data', :action => 'yaml_import'} do |f| %>
        <%= f.text_area :yaml %><br />
        <input type="submit" value="Daten importieren">
      <% end %>
    </p>
  </div><!-- End of feeds -->
</div><!-- End of display_box -->

app/views/data/yaml_form.en.html.erb
<div id="display_box">
  <div id="feeds">
    <div id="feedlegend">
      <p><b>Beware</b>: all your current data will be destroyed before importing
        the YAML file, so if you have access to the database, we strongly recommend
        backing up the database right now in case that anything goes wrong.
      </p>
      <p>Paste the contents of the YAML file you exported into the text box below:</p>
    </div>
    <p>
      <%= form_for :import, @import, :url => {:controller => 'data', :action => 'yaml_import'} do |f| %>
        <%= f.text_area :yaml %><br />
        <input type="submit" value="Import data">
      <% end %>
    </p>
  </div><!-- End of feeds -->
</div><!-- End of display_box -->

app/views/data/yaml_import.html.erb
<% if !(@errmessage == '') %>
  <p><%= t('data.import_errors') %>:<pre><%= @errmessage %></pre></p>
<% else %>
  <p><%= t('data.import_successful') %></p>
<% end %>